# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  firge = {
    pname = "firge";
    version = "v0.3.0";
    src = fetchurl {
      url = "https://github.com/yuru7/Firge/releases/download/v0.3.0/Firge_v0.3.0.zip";
      sha256 = "sha256-yYb2IQAKZZgGTH4geDIu0CBAr094BNJYAz35SbNbBSc=";
    };
  };
  firge-nerd = {
    pname = "firge-nerd";
    version = "v0.3.0";
    src = fetchurl {
      url = "https://github.com/yuru7/Firge/releases/download/v0.3.0/FirgeNerd_v0.3.0.zip";
      sha256 = "sha256-VM12N4+8UCX0LUQdlcpuwdPsxCcOYQdViED+18BM/k8=";
    };
  };
  pinact = {
    pname = "pinact";
    version = "v1.2.0";
    src = fetchFromGitHub {
      owner = "suzuki-shunsuke";
      repo = "pinact";
      rev = "v1.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-OmWt4EyUHZyQDIj1Uro+bnC29MNi6wlXO2ksRP84F2U=";
    };
  };
}
